config/routes.rb
FbPopularity::Application.routes.draw do
  resources :crushes

  resources :auth_tokens
	
	match 'crushes/fetch/:id' => 'crushes#fetch'	

end

app/models/auth_token.rb
class AuthToken < ActiveRecord::Base
  attr_accessible :fbId, :token
end

app/models/crush.rb
class Crush < ActiveRecord::Base
  attr_accessible :crush, :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/auth_tokens_controller.rb
class AuthTokensController < ApplicationController
  # GET /auth_tokens
  # GET /auth_tokens.json
  def index
    @auth_tokens = AuthToken.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @auth_tokens }
    end
  end

  # GET /auth_tokens/1
  # GET /auth_tokens/1.json
  def show
    @auth_token = AuthToken.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @auth_token }
    end
  end

  # GET /auth_tokens/new
  # GET /auth_tokens/new.json
  def new
    @auth_token = AuthToken.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @auth_token }
    end
  end

  # GET /auth_tokens/1/edit
  def edit
    @auth_token = AuthToken.find(params[:id])
  end

  # POST /auth_tokens
  # POST /auth_tokens.json
  def create
    @auth_token = AuthToken.new(params[:auth_token])

    respond_to do |format|
      if @auth_token.save
        format.html { redirect_to @auth_token, notice: 'Auth token was successfully created.' }
        format.json { render json: @auth_token, status: :created, location: @auth_token }
      else
        format.html { render action: "new" }
        format.json { render json: @auth_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /auth_tokens/1
  # PUT /auth_tokens/1.json
  def update
    @auth_token = AuthToken.find(params[:id])

    respond_to do |format|
      if @auth_token.update_attributes(params[:auth_token])
        format.html { redirect_to @auth_token, notice: 'Auth token was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @auth_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auth_tokens/1
  # DELETE /auth_tokens/1.json
  def destroy
    @auth_token = AuthToken.find(params[:id])
    @auth_token.destroy

    respond_to do |format|
      format.html { redirect_to auth_tokens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/crushes_controller.rb
class CrushesController < ApplicationController
  # GET /crushes
  # GET /crushes.json
  def index
    @crushes = Crush.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @crushes }
    end
  end

	# GET /crushes/fetch/user_id
	# GET /crushes/fetch/user_id.json

  def fetch
    @crush = Crush.where(:user => params[:id])

    respond_to do |format|
      format.json { render json: @crush }
    end
  end

  # GET /crushes/1
  # GET /crushes/1.json
  def show
    @crush = Crush.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @crush }
    end
  end

  # GET /crushes/new
  # GET /crushes/new.json
  def new
    @crush = Crush.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @crush }
    end
  end

  # GET /crushes/1/edit
  def edit
    @crush = Crush.find(params[:id])
  end

  # POST /crushes
  # POST /crushes.json
  def create
    @crush = Crush.new(params[:crush])

    respond_to do |format|
      if @crush.save
        format.html { redirect_to @crush, notice: 'Crush was successfully created.' }
        format.json { render json: @crush, status: :created, location: @crush }
      else
        format.html { render action: "new" }
        format.json { render json: @crush.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crushes/1
  # PUT /crushes/1.json
  def update
    @crush = Crush.find(params[:id])

    respond_to do |format|
      if @crush.update_attributes(params[:crush])
        format.html { redirect_to @crush, notice: 'Crush was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @crush.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crushes/1
  # DELETE /crushes/1.json
  def destroy
    @crush = Crush.find(params[:id])
    @crush.destroy

    respond_to do |format|
      format.html { redirect_to crushes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_tokens_helper.rb
module AuthTokensHelper
end

app/helpers/crushes_helper.rb
module CrushesHelper
end

app/views/auth_tokens/_form.html.erb
<%= form_for(@auth_token) do |f| %>
  <% if @auth_token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auth_token.errors.count, "error") %> prohibited this auth_token from being saved:</h2>

      <ul>
      <% @auth_token.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fbId %><br />
    <%= f.text_field :fbId %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auth_tokens/edit.html.erb
<h1>Editing auth_token</h1>

<%= render 'form' %>

<%= link_to 'Show', @auth_token %> |
<%= link_to 'Back', auth_tokens_path %>

app/views/auth_tokens/index.html.erb
<h1>Listing auth_tokens</h1>

<table>
  <tr>
    <th>Fbid</th>
    <th>Token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @auth_tokens.each do |auth_token| %>
  <tr>
    <td><%= auth_token.fbId %></td>
    <td><%= auth_token.token %></td>
    <td><%= link_to 'Show', auth_token %></td>
    <td><%= link_to 'Edit', edit_auth_token_path(auth_token) %></td>
    <td><%= link_to 'Destroy', auth_token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Auth token', new_auth_token_path %>

app/views/auth_tokens/new.html.erb
<h1>New auth_token</h1>

<%= render 'form' %>

<%= link_to 'Back', auth_tokens_path %>

app/views/auth_tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fbid:</b>
  <%= @auth_token.fbId %>
</p>

<p>
  <b>Token:</b>
  <%= @auth_token.token %>
</p>


<%= link_to 'Edit', edit_auth_token_path(@auth_token) %> |
<%= link_to 'Back', auth_tokens_path %>

app/views/crushes/_form.html.erb
<%= form_for(@crush) do |f| %>
  <% if @crush.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crush.errors.count, "error") %> prohibited this crush from being saved:</h2>

      <ul>
      <% @crush.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :crush %><br />
    <%= f.text_field :crush %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crushes/edit.html.erb
<h1>Editing crush</h1>

<%= render 'form' %>

<%= link_to 'Show', @crush %> |
<%= link_to 'Back', crushes_path %>

app/views/crushes/index.html.erb
<h1>Listing crushes</h1>

<table>
  <tr>
    <th>User</th>
    <th>Crush</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @crushes.each do |crush| %>
  <tr>
    <td><%= crush.user %></td>
    <td><%= crush.crush %></td>
    <td><%= link_to 'Show', crush %></td>
    <td><%= link_to 'Edit', edit_crush_path(crush) %></td>
    <td><%= link_to 'Destroy', crush, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Crush', new_crush_path %>

app/views/crushes/new.html.erb
<h1>New crush</h1>

<%= render 'form' %>

<%= link_to 'Back', crushes_path %>

app/views/crushes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @crush.user %>
</p>

<p>
  <b>Crush:</b>
  <%= @crush.crush %>
</p>


<%= link_to 'Edit', edit_crush_path(@crush) %> |
<%= link_to 'Back', crushes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FbPopularity</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>